<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><EnableWindowsTargeting>true</EnableWindowsTargeting><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><ApplicationManifest>app.manifest</ApplicationManifest><AssemblyName>MenuBarStats</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../MenuBarStats.Core/MenuBarStats.Core.csproj"/></ItemGroup>
</Project>
